comment:
  layout: header, changes, diff, sunburst
coverage:
  precision: 2
  round: down
  range: "65...100"
  status:
    patch:
      default:
        target: "85.0"
    project:
      default:
        target: auto
